/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laksh
 */
public class FuntionHallAdd extends javax.swing.JFrame {

    /**
     * Creates new form funtionHall
     */
    public FuntionHallAdd() {
        initComponents();
        Connect();
        autoID();
        Load_funtionHall();
    }
    
    
    Connection con;
    PreparedStatement pst;
    DefaultTableModel d;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost/hotelmanagement","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
     public void autoID()
    {
        try {
            Statement s =con.createStatement();
            ResultSet rs =s.executeQuery("select MAX(fid)from function");
            rs.next();
            rs.getString("MAX(fid)");
            if(rs.getString("MAX(fid)")==null)
            {
                jLabel7.setText("R0001");
            }
            else
            {
                long id = Long.parseLong(rs.getString("MAX(fid)").substring(2,rs.getString("MAX(fid)").length()));
                id++;
                jLabel7.setText("R0"+String.format("%03d",id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
     public void Load_funtionHall()
    {
        int c;
        try {
            pst =con.prepareStatement("select * from function");
            ResultSet rs =pst.executeQuery();
            
            ResultSetMetaData rsd =rs.getMetaData();
            c = rsd.getColumnCount();
            
            d = (DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 =new Vector();
                for(int i=1; i<=c; i++)
                {
                    v2.add(rs.getString("fid"));
                    v2.add(rs.getString("ftype"));
                    v2.add(rs.getString("htype"));
                    v2.add(rs.getString("hfeature"));
                    v2.add(rs.getString("capacity"));
                    v2.add(rs.getString("amount"));
                }
                d.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtfunction = new javax.swing.JComboBox<>();
        txtfeature = new javax.swing.JComboBox<>();
        txttype = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtcapacity = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Function Hall");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 10, 390, 42);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 204));
        jLabel3.setText("Function Hall Num");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 230, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 204));
        jLabel4.setText("Function Type");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 170, 180, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 204));
        jLabel5.setText("Hall Features");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 290, 200, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 204));
        jLabel6.setText("Price");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 420, 150, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 90, 150, 40);

        txtfunction.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtfunction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Birthday Celebrations", "Company Party", "Ceremony", "Anniversary Celebrations", "Bachelorette party", "Bachelorette party", "Engagement and Ring Ceremony", "Farewell", " " }));
        jPanel1.add(txtfunction);
        txtfunction.setBounds(220, 170, 190, 30);

        txtfeature.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtfeature.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liqure-Served", "Air Conditioned", "Dj", "Dance Floor", " ", " " }));
        jPanel1.add(txtfeature);
        txtfeature.setBounds(220, 300, 190, 30);

        txttype.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquet / Wedding Style ", "Board Meeting Style", "Herringbone or fish bone style", "Hollow Square Style", "Lecture Room - Training Room Style", "School Room", "T Shape - Style", "Theater Style", "U Style" }));
        jPanel1.add(txttype);
        txttype.setBounds(220, 230, 190, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 204));
        jLabel8.setText("Venue Capacity");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 360, 200, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 204));
        jLabel9.setText("Hall Type");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 230, 200, 30);

        txtamount.setBackground(new java.awt.Color(204, 204, 204));
        txtamount.setText("RS :");
        txtamount.setToolTipText("RS:");
        jPanel1.add(txtamount);
        txtamount.setBounds(220, 430, 190, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall No", "Function Type", "Hall Type", "Feature", "Venue Capasity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 100, 550, 402);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 560, 61, 30);

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 560, 53, 30);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(390, 560, 63, 30);

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(650, 560, 59, 30);

        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(790, 560, 63, 30);

        txtcapacity.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtcapacity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Less Than 25", "26 to 50", "51 to 100", "101 to 150", "151 to 200", "201 to 250", "251 to 300", "301 to 350", "More Than 350 " }));
        jPanel1.add(txtcapacity);
        txtcapacity.setBounds(220, 360, 190, 30);

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(510, 560, 69, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/function hall.jpg"))); // NOI18N
        jLabel1.setToolTipText("Liqure-Served\nAir Conditioned\nDj\n");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-270, -10, 1280, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txtamount.getText().isEmpty())
       {
        JOptionPane.showMessageDialog(this,"Found Empty Filed." );
       }
       else 
       {
        String hallno =jLabel7.getText();
        String funtype =txtfunction.getSelectedItem().toString();
        String halltype =txttype.getSelectedItem().toString();
        String hallfeature =txtfeature.getSelectedItem().toString();
        String capacity =txtcapacity.getSelectedItem().toString();  
        String amount =txtamount.getText();
        try {
            pst =con.prepareStatement("insert into function(fid , ftype ,htype,hfeature,capacity,amount) values(?,?,?,?,?,?)");
            pst.setString(1, hallno);
            pst.setString(2, funtype);
            pst.setString(3, halltype);
            pst.setString(4, hallfeature);
            pst.setString(5, capacity);
            pst.setString(6, amount);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Function Added");
            
            txtfunction.setSelectedIndex(-1);
            txttype.setSelectedIndex(-1);
            txtfeature.setSelectedIndex(-1);
            txtcapacity.setSelectedIndex(-1);
            txtamount.setText("");
            autoID();
            Load_funtionHall();
             
        } catch (SQLException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(txtfunction.getSelectedItem().toString().isEmpty()||txttype.getSelectedItem().toString().isEmpty()||txtcapacity.getSelectedItem().toString().isEmpty()|| txtfeature.getSelectedItem().toString().isEmpty()||txtamount.getText().isEmpty())
        {
              JOptionPane.showMessageDialog(this, "You Don't  Edit Any Item " );
        }
        else
        {
         {
        String hallno =jLabel7.getText();
        String funtype =txtfunction.getSelectedItem().toString();
        String halltype =txttype.getSelectedItem().toString();
        String hallfeature =txtfeature.getSelectedItem().toString();
        String capacity =txtcapacity.getSelectedItem().toString();  
        String amount =txtamount.getText();
         
        try {
            pst =con.prepareStatement("update function set ftype = ?, htype = ? ,hfeature = ?,capacity=?,amount =? where fid = ?");
           
            pst.setString(1, funtype);
            pst.setString(2, halltype);
            pst.setString(3, hallfeature);
            pst.setString(4, capacity);
            pst.setString(5, amount); 
            pst.setString(6, hallno);
            pst.executeUpdate();  
            JOptionPane.showMessageDialog(this,"Function Edit");
            
            txtfunction.setSelectedIndex(-1);
            txttype.setSelectedIndex(-1);
            txtfeature.setSelectedIndex(-1);
            txtcapacity.setSelectedIndex(-1);
            txtamount.setText("");
            autoID();
            Load_funtionHall();
            jButton1.setEnabled(true);
             
        } catch (SQLException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
      }    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:  d = (DefaultTableModel)jTable1.getModel();
        int selectIndex =jTable1.getSelectedRow();
        jLabel7.setText(d.getValueAt(selectIndex, 0).toString());
        txtfunction.setSelectedItem(d.getValueAt(selectIndex, 1).toString());
        txttype.setSelectedItem(d.getValueAt(selectIndex, 2).toString());
        txtfeature.setSelectedItem(d.getValueAt(selectIndex, 3).toString());
        txtcapacity.setSelectedItem(d.getValueAt(selectIndex, 4).toString());
        txtamount.setText(d.getValueAt(selectIndex, 5).toString());
        jButton1.setEnabled(false);
        
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          d = (DefaultTableModel)jTable1.getModel();
        int selectIndex =jTable1.getSelectedRow();

        jLabel7.setText(d.getValueAt(selectIndex, 0).toString());
        txtfunction.setSelectedItem(d.getValueAt(selectIndex, 1).toString());
        txttype.setSelectedItem(d.getValueAt(selectIndex, 2).toString());
        txtfeature.setSelectedItem(d.getValueAt(selectIndex, 3).toString());
        txtcapacity.setSelectedItem(d.getValueAt(selectIndex, 4).toString());
        txtamount.setText(d.getValueAt(selectIndex, 5).toString());
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          
            txtfunction.setSelectedIndex(-1);
            txttype.setSelectedIndex(-1);
            txtfeature.setSelectedIndex(-1);
            txtcapacity.setSelectedIndex(-1);
            txtamount.setText("");
            autoID();
            Load_funtionHall();
            jButton1.setEnabled(true);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int close =JOptionPane.showConfirmDialog(null,"Delete Item","Select",JOptionPane.YES_NO_OPTION);
        String function =jLabel7.getText();
 
        try {
            pst =con.prepareStatement("delete from function where fid = ?");
            pst.setString(1, function); 
            pst.executeUpdate();
            
            txtfunction.setSelectedIndex(-1);
            txttype.setSelectedIndex(-1);
            txtfeature.setSelectedIndex(-1);
            txtcapacity.setSelectedIndex(-1);
            txtamount.setText("");
            autoID();
            Load_funtionHall();
            jButton1.setEnabled(true);
             
        } catch (SQLException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AdminMainManu min =new AdminMainManu();
        min.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int close =JOptionPane.showConfirmDialog(null,"Close The Application","Select",JOptionPane.YES_NO_OPTION);
        if(close==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuntionHallAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuntionHallAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuntionHallAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuntionHallAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuntionHallAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtamount;
    private javax.swing.JComboBox<String> txtcapacity;
    private javax.swing.JComboBox<String> txtfeature;
    private javax.swing.JComboBox<String> txtfunction;
    private javax.swing.JComboBox<String> txttype;
    // End of variables declaration//GEN-END:variables
}
