/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laksh
 */
public class UserConferenceReservation extends javax.swing.JFrame {

public UserConferenceReservation() {
        initComponents();
        Connect();
        autoID();
        RoomTypeL();
        amount();
        capacity();
        status();
    }
    
    Connection con;
    PreparedStatement pst;
    DefaultTableModel d;
    
public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost/hotelmanagement","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
public void RoomTypeL()
      {
        try {
            pst=con.prepareStatement("select Distinct crtype from  conference");  
            ResultSet rs = pst.executeQuery();
            txtrtype.removeAllItems();
            
            while(rs.next())
            {
                txtrtype.addItem(rs.getString("crtype"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    
public void amount()
      {
        try {
            pst=con.prepareStatement("select Distinct amount from conference");  
            ResultSet rs = pst.executeQuery();
            txtamount.removeAllItems();
            
            while(rs.next())
            {
                txtamount.addItem(rs.getString("amount"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
 

public void status()
      {
        try {
            pst=con.prepareStatement("select Distinct status from conferencereservation");  
            ResultSet rs = pst.executeQuery();
            txtstatus.removeAllItems();
            
            while(rs.next())
            {
                txtstatus.addItem(rs.getString("status"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
      }

public void capacity()
      {
        try {
            pst=con.prepareStatement("select Distinct capacity from conference");  
            ResultSet rs = pst.executeQuery();
            txtcapacity.removeAllItems();
            
            while(rs.next())
            {
                txtcapacity.addItem(rs.getString("capacity"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    
    
    
public void autoID()
    {
        try {
            Statement s =con.createStatement();
            ResultSet rs =s.executeQuery("select MAX(cid)from  conferencereservation");
            rs.next();
            rs.getString("MAX(cid)");
            if(rs.getString("MAX(cid)")==null)
            {
                jLabel13.setText("RE001");
            }
            else
            {
                long id = Long.parseLong(rs.getString("MAX(cid)").substring(2,rs.getString("MAX(cid)").length()));
                id++;
                jLabel13.setText("RE"+String.format("%03d",id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        txtnam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txttime = new javax.swing.JTextField();
        txtrtype = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtamount = new javax.swing.JComboBox<>();
        txtcapacity = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reservation Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 130, 220, 24);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(360, 130, 120, 30);

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setText("institution Name And Adress");
        jPanel1.add(txtname);
        txtname.setBounds(120, 190, 240, 20);

        txtnam.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtnam);
        txtnam.setBounds(360, 190, 250, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 240, 140, 24);

        txtmobile.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtmobile);
        txtmobile.setBounds(360, 250, 250, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email Adress");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 300, 230, 20);

        txtemail.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtemail);
        txtemail.setBounds(360, 310, 250, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Reserved Date");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 370, 250, 24);
        jPanel1.add(txtdate);
        txtdate.setBounds(360, 370, 250, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reserved Time");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(120, 430, 190, 22);

        txttime.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txttime);
        txttime.setBounds(360, 430, 250, 30);

        txtrtype.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtrtype);
        txtrtype.setBounds(360, 500, 250, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Reservation Room Type");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(120, 500, 240, 24);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Amount");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(120, 560, 150, 24);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 750, 61, 25);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(650, 750, 63, 25);

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(760, 750, 59, 25);

        jButton6.setBackground(new java.awt.Color(255, 204, 204));
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(550, 750, 63, 25);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Conference Room Reservation");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 40, 500, 60);

        jPanel1.add(txtamount);
        txtamount.setBounds(360, 560, 250, 30);

        txtcapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcapacityActionPerformed(evt);
            }
        });
        jPanel1.add(txtcapacity);
        txtcapacity.setBounds(360, 620, 250, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Capacity");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(120, 620, 150, 24);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 670, 190, 24);

        txtstatus.setBackground(new java.awt.Color(204, 204, 204));
        txtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatusActionPerformed(evt);
            }
        });
        jPanel1.add(txtstatus);
        txtstatus.setBounds(360, 670, 240, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Conference room.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-240, -100, 1080, 880);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if(txtamount.getSelectedItem().toString().isEmpty())
       {
            JOptionPane.showMessageDialog(this,"Found Empty Filed." );
       }
       else { 
        String cno =jLabel13.getText();
        String name =txtnam.getText();
        String mobile =txtmobile.getText();
        String email =txtemail.getText();
        
        SimpleDateFormat df1 =new SimpleDateFormat("yyyy-MM-dd");
        String Date=df1.format(txtdate.getDate());
        
        String time =txttime.getText().toString();
        String rtype =txtrtype.getSelectedItem().toString();
        String amount =txtamount.getSelectedItem().toString();
        String capacity =txtcapacity.getSelectedItem().toString();
        String status =txtstatus.getSelectedItem().toString(); 
        try {
            pst =con.prepareStatement("insert into conferencereservation (cid ,name,mobile,email,date,time,rtype,amount,capacity,status) values(?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, cno);
            pst.setString(2, name);
            pst.setString(3, mobile);
            pst.setString(4, email);
            pst.setString(5, Date);
            pst.setString(6, time);
            pst.setString(7, rtype);
            pst.setString(8, amount);
            pst.setString(9, capacity);
            pst.setString(10, status);
           
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Reservation Conference Room Added");
           
            
            txtnam.setText("");
            txtmobile.setText("");
            txtemail.setText("");
            txttime.setText("");
            txtrtype.setSelectedIndex(-1);
            txtamount.setSelectedIndex(-1);
            txtcapacity.setSelectedIndex(-1);;
            txtstatus.setSelectedIndex(-1);;
            autoID();
            
        } catch (SQLException ex) {
            Logger.getLogger(RoomAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtnam.setText("");
        txtmobile.setText("");
        txtemail.setText("");
        txttime.setText("");
        txtrtype.setSelectedIndex(-1);
        txtamount.setSelectedIndex(-1);
        txtcapacity.setSelectedIndex(-1);
        txtstatus.setSelectedIndex(-1);
        autoID();
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       UserMainManu min =new UserMainManu();
        min.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int close =JOptionPane.showConfirmDialog(null,"Close The Application","Select",JOptionPane.YES_NO_OPTION);
        if(close==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtcapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcapacityActionPerformed

    private void txtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserConferenceReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserConferenceReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserConferenceReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserConferenceReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserConferenceReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> txtamount;
    private javax.swing.JComboBox<String> txtcapacity;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtnam;
    private javax.swing.JLabel txtname;
    private javax.swing.JComboBox<String> txtrtype;
    private javax.swing.JComboBox<String> txtstatus;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
