const bags =[
    {
        id:1,
        name:'school bag',
        pricFe:'1800',
        shipping:"150",
        ass:require('../asset/pic16.png'),
        about:'high quality',
    },
    {
        id:2,
        name:'school bag',
        price:'1800',
        shipping:"150",
        ass:require('../asset/pic16.png'),
        about:'high quality',
    },
    {
        id:4,
        name:'school bag',
        price:'1800',
        shipping:"150",
        ass:require('../asset/pic16.png'),
        about:'high quality',
    },
    {
        id:5,
        name:'school bag',
        price:'1800',
        shipping:"150",
        ass:require('../asset/pic16.png'),
        about:'high quality',
    },
    {
        id:6,
        name:'school bag',
        price:'1800',
        shipping:"150",
        ass:require('../asset/pic16.png'),
        about:'high quality',
    },
    {
        id:7,
        name:'school bag',
        price:'1800',
        shipping:"150",
        ass:require('../asset/pic16.png'),
        about:'high quality',
    },
    {
        id:8,
        name:'school bag',
        price:'1800',
        shipping:"150",
        ass:require('../asset/pic16.png'),
        about:'high quality',
    },
    {
        id:9,
        name:'school bag',
        price:'1800',
        shipping:"150",
        ass:require('../asset/pic16.png'),
        about:'high quality',
    },
    {
        id:10,
        name:'school bag',
        price:'1800',
        shipping:"150",
        ass:require('../asset/pic16.png'),
        about:'high quality',
    },
    {
        id:11,
        name:'school bag',
        price:'1800',
        shipping:"150",
        ass:require('../asset/pic16.png'),
        about:'high quality',
    },
    ]
export default bags;